[build-system]
requires = ["setuptools",
    "wheel",
    "setuptools_scm",
    "numpy",
    "scipy",
    "matplotlib",
    "sunpy",
    "paramiko",
    "pyvista"
]
build-backend = "setuptools.build_meta"

[project]
python_requires = ">=3.10,<3.11"